<?php 

if ( ! defined( 'ABSPATH' ) ) exit;

return apply_filters( 'ekwc_get_default_options',
    array(
        'ekwc_general_setting'  => array(
            'enable'                => 'yes',
            'enable_compare'        => 'yes',
            'enable_wishlist'       => 'yes',
            'enable_quick_view'     => 'yes',
            'single_position'       => 'woocommerce_product_thumbnails-0',
            'icon_position_single'  => 'top-right',
            'icon_viewport_single'  => 'vertical',
            'shop_position'         => 'woocommerce_before_shop_loop_item-10',
            'icon_display_type'     => 'fixed',
            'icon_position_shop'    => 'top-right',
            'icon_viewport_shop'    => 'vertical',
            'icon_bg_color'         => '#ffffff',
            'icon_hover_bg_color'   => '#274c4f',
            'compare_img'           => EKWC_URL . 'assets/img/compare.svg',
            'wishlist_img'          => EKWC_URL . 'assets/img//wishlist/heart-outline.svg',
            'quick_view_img'        => EKWC_URL . 'assets/img/quick-view.svg',
        ),
        'ekwc_compare_genral'   => array(
            'compare_btn_text'      => 'Compare Product',
            'remove_btn_text'       => 'Remove',
            'open_auto_lightbox'    => 'yes',
        ),
        'ekwc_compare_table'    => array(
            'compare_table_title'   => 'Product Comparison',
            'show_image'            => 'yes',
            'show_title'            => 'yes',
            'show_price'            => 'yes',
            'show_rating'           => 'yes',
            'show_description'      => 'yes',
            'show_sku'              => 'yes',
            'show_availability'     => 'yes',
            'show_weight'           => 'yes',
            'show_dimensions'       => 'yes',
            'show_add_to_cart'      => 'yes',
            'pcwc_attr_color'       => 'no',
            'pcwc_attr_size'        => 'no',
        ),
        'ekwc_compare_style'    => array(
            'compare_button_bg_color'   => '#274c4f',
            'compare_button_text_color' => '#ffffff',
            'product_compare_style'     => 'compare-table',
            'comparison_table_layout'   => 'vertical',
            'style_1_button_color'      => '#0a0202',
            'style_1_button_text_color' => '#ffffff',
        ),
        'ekwc_compare_premium'  => array(
            'hide_similarities'                         => 'no',
            'highlight_differences'                     => 'no',
            'related_product_compare'                   => 'no',
            'shareable_comparison_table_url'            => 'no',
            'enable_sticky_bar_of_product_comparison'   => 'no',
        ),

        'ekwc_shipping_bar_settings'     => array(
            'enable'                        => 'yes',
            'mobile'                        => 'yes',
            'shipping_zone'                 => '1',
            'bar_position'                  => 'top_bar',
            'topbar_style'                  => 'style1',
            'show_minicart'                 => 'woocommerce_mini_cart_contents',
            'show_cart'                     => 'woocommerce_proceed_to_checkout',
            'show_checkout'                 => 'woocommerce_checkout_before_customer_details',
            'checkout_style'                => 'style1',
            'show_product'                  => 'woocommerce_before_single_product',
            'bg_color'                      => '#d2f2ff',
            'text_color'                    => '#3e3f5e',
            'link_color'                    => '#83b834',
            'font_size'                     => '18',
            'text_align'                    => 'center',
            'enable_progress'               => 'yes',
            'progress_bg_color'             => '#e7e7ef',
            'curr_progress_color'           => '#45defe',
            'progress_text_color'           => '#ffffff',
            'custom_css'                    => '',
            'sp_progress_bg_color'          => '#e7e7ef',
            'sp_curr_progress_color'        => '#45defe',
            'sp_text_color'                 => '#3e3f5e',
            'mc_progress_bg_color'          => '#e7e7ef',
            'mc_curr_progress_color'        => '#45defe',
            'mc_text_color'                 => '#3e3f5e',
            'cart_progress_bg_color'        => '#e7e7ef',
            'cart_curr_progress_color'      => '#45defe',
            'cart_text_color'               => '#3e3f5e',
            'checkout_progress_bg_color'    => '#e7e7ef',
            'checkout_curr_progress_color'  => '#45defe',
            'checkout_text_color'           => '#3e3f5e',
            'announcement_notifications'    => 'Free shipping for billing over {min_amount}',
            'purchased_notifications'       => 'You have purchased {total_amounts} of {min_amount}',
            'success_notifications'         => 'Congratulation! You have got free shipping. Go to {checkout_page}',
            'error_notifications'           => 'You are missing {missing_amount} to get Free Shipping. Continue {shopping}',
            'intial_delay'                  => '1',
            'closebar_button'               => 'yes',
            'is_time_to_disappear'          => 'no',
            'time_to_disappear'             => '10',
            'enable_gift_box'               => 'yes',
            'giftbox_position'              => 'bottom_right',
            'gift_icon_url'                 => EKWC_URL . 'assets/img/free-shipping-bar/free-shipping.png',
            'giftbox_style'                 => 'style1',
            'continue_shopping_clicks'      => '0',
            'home_page'                     => 'no',
            'cart_page'                     => 'no',
            'shop_page'                     => 'no',
            'checkout_page'                 => 'no',
            'single_product_page'           => 'no',
            'product_cat_page'              => 'no'
        ),

        'ekwc_wishlist_setting'    => array(
            'after_add_to_wishlist_action'        => 'view_wishlist_link',
            'multi_wishlist_feature'              => 'no',
            'add_to_wishlist_text'                => 'Add to Wishlist',
            'added_to_wishlist_text'              => 'Added to Wishlist',
            'remove_from_wishlist_text'           => 'Remove from Wishlist',
            'browse_wishlist_text'                => 'Browse Wishlist',
            'product_already_in_wishlist_text'    => 'The product is already in your wishlist!',
            'create_wishlist_btn_text'            => 'Create wishlist',
            'default_wishlist_name'               => 'My Wishlist',
            'wishlist_table_title'                => 'Wishlists on Essential Kit',
            'wishlist_share_title'                => 'Share on:',
            'add_to_cart_text'                    => 'Add to Cart',
            'wishlist_btn_style'                  => 'link',
            'add_to_wishlist_icon'                => EKWC_URL . 'assets/img/wishlist/heart-outline.svg',
            'added_to_wishlist_icon'              => EKWC_URL . 'assets/img/wishlist/heart.svg',
            'add_to_cart_btn_style'               => 'button',
            'add_to_cart_btn_text_color'          => '#ffffff',
            'add_to_cart_btn_bg_color'            => '#274c4f',
            'add_to_cart_btn_hover_text_color'    => '#ffffff',
            'add_to_cart_btn_hover_bg_color'      => '#2a4b4f',
            'facebook_icon'                       => EKWC_URL . 'assets/img/wishlist/facebook.svg',
            'twitter_icon'                        => EKWC_URL . 'assets/img/wishlist/twitter.svg',
            'pinterest_icon'                      => EKWC_URL . 'assets/img/wishlist/pinterest.svg',
            'email_icon'                          => EKWC_URL . 'assets/img/wishlist/email.png',
            'whatsapp_icon'                       => EKWC_URL . 'assets/img/wishlist/whatsapp.png',
            'wishlist_page'                       => '',
            'ekwc_price_show'                     => 'yes',
            'ekwc_stock_show'                     => 'yes',
            'ekwc_show_dateadded'                 => 'yes',
            'ekwc_add_to_cart_show'               => 'yes',
            'ekwc_left_show_remove'               => 'yes',
            'ekwc_right_remove_button'            => 'no',
            'ekwc_redirect_to_cart'               => 'yes',
            'ekwc_remove_on_add_to_cart'          => 'no',
            'ekwc_share_wishlist'                 => 'yes',
            'ekwc_share_facebook'                 => 'yes',
            'ekwc_share_twitter'                  => 'yes',
            'ekwc_share_pinterest'                => 'yes',
            'ekwc_share_email'                    => 'yes',
            'ekwc_share_whatsapp'                 => 'yes',
            'wishlist_btn_text_color'             => '#ffffff',
            'wishlist_btn_bg_color'               => '#274c4f',
            'wishlist_btn_hover_bg_color'         => '#ffffff',
            'wishlist_btn_hover_text_color'       => '#2a4b4f',
        ),

        'ekwc_quick_view_setting'   => array(
            'enable_on_mobile'                          => 'yes',
            'enable_quick_view_wishlist'                => 'yes',
            'product_description'                       => 'full',
            'product_image_dimensions'                  => array(
                                                                'width'     => '300',
                                                                'height'    => '300',
                                                            ),
            'quick_view_style'                          => 'window_modal',
            'quick_view_button_label'                   => 'Quick View',
            'content_background'                        => '#ffffff',
            'overlay_color'                             => '#000000',
            'close_icon_color'                          => '#0a0a0a',
            'close_icon_hover'                          => '#0a0404',
            'button_bg_color'                           => '#274c4f',
            'button_bg_hover'                           => '#2a4b4f',
            'button_text_color'                         => '#ffffff',
            'button_text_hover'                         => '#ffffff',
            'main_text_color'                           => '#404040',
            'star_color'                                => '#fcc640',
            'add_to_cart_btn_bg_color'                  => '#274c4f',
            'add_to_cart_btn_bg_hover_color'            => '#2a4b4f',
            'add_to_cart_text_color'                    => '#ffffff',
            'add_to_cart_text_hover_color'              => '#ffffff',
            'show_product_image'                        => 'yes',
            'show_product_name'                         => 'yes',
            'show_product_rating'                       => 'yes',
            'show_product_price'                        => 'yes',
            'show_add_to_cart'                          => 'yes',
            'show_wishlist_button'                      => 'yes',
            'show_product_meta'                         => 'yes',
            'close_popup_after_add_to_cart'             => 'yes',
            'redirect_to_checkout_after_add_to_cart'    => 'no',
            'enable_facebook_share'                     => 'yes',
            'enable_x_share'                            => 'yes',
            'enable_pinterest_share'                    => 'yes',
            'enable_email_share'                        => 'yes',
            'enable_whatsapp_share'                     => 'yes',
            'overlay_opacity'                           => '0.5',
        ),
        'scwc_size_chart_setting' => array(
                'popup_library'     => 'magnific',
                'effect'            => 'mfp-zoom-in',
                'position'          => 'woocommerce_product_tabs-0',
                'label'             => 'Size Chart',
        ),
    )
);
